import pygame
import chess
import chess.engine
import tensorflow as tf
import numpy as np



# this file is generated by ai just for fun to see the model in work






# === CONFIG ===
WIDTH, HEIGHT = 512, 512
SQUARE_SIZE = WIDTH // 8
LIGHT = (240, 217, 181)
DARK = (181, 136, 99)
PIECES_IMG_PATH = "assets"  # folder with piece images
MODEL_PATH = "chess_model_improved.h5"

# === Load model ===
model = tf.keras.models.load_model(MODEL_PATH)

def fen_to_board(fen: str) -> np.ndarray:
    piece_map = {
        'P': 1, 'N': 2, 'B': 3, 'R': 4, 'Q': 5, 'K': 6,
        'p': -1, 'n': -2, 'b': -3, 'r': -4, 'q': -5, 'k': -6
    }
    board = []
    rows = fen.split(' ')[0].split('/')
    for row in rows:
        for char in row:
            if char.isdigit():
                board.extend([0] * int(char))
            else:
                board.append(piece_map[char])
    return np.array(board, dtype=np.float32) / 6.0

def predict_eval(model, board: chess.Board) -> float:
    board_input = fen_to_board(board.fen()).reshape(1, 64)
    eval_normalized = model.predict(board_input, verbose=0)[0][0]
    return eval_normalized * 10

def get_best_move(model, board: chess.Board) -> chess.Move:
    best_move = None
    best_eval = -float('inf') if board.turn == chess.WHITE else float('inf')

    for move in board.legal_moves:
        board.push(move)
        eval_score = predict_eval(model, board)
        board.pop()

        if board.turn == chess.WHITE and eval_score > best_eval:
            best_eval = eval_score
            best_move = move
        elif board.turn == chess.BLACK and eval_score < best_eval:
            best_eval = eval_score
            best_move = move

    return best_move

def load_images():
    pieces = {}
    for piece in ['P', 'N', 'B', 'R', 'Q', 'K',
                  'p', 'n', 'b', 'r', 'q', 'k']:
        image = pygame.image.load(f"{PIECES_IMG_PATH}/{piece}.png")
        image = pygame.transform.scale(image, (SQUARE_SIZE, SQUARE_SIZE))
        pieces[piece] = image
    return pieces

def draw_board(win):
    for row in range(8):
        for col in range(8):
            color = LIGHT if (row + col) % 2 == 0 else DARK
            pygame.draw.rect(win, color, (col*SQUARE_SIZE, row*SQUARE_SIZE, SQUARE_SIZE, SQUARE_SIZE))

def draw_pieces(win, board, images):
    for square in chess.SQUARES:
        piece = board.piece_at(square)
        if piece:
            row = 7 - square // 8
            col = square % 8
            win.blit(images[str(piece)], (col*SQUARE_SIZE, row*SQUARE_SIZE))

def get_square(pos):
    x, y = pos
    col = x // SQUARE_SIZE
    row = 7 - (y // SQUARE_SIZE)
    return chess.square(col, row)

def main():
    pygame.init()
    win = pygame.display.set_mode((WIDTH, HEIGHT))
    pygame.display.set_caption("Chess vs Model")
    clock = pygame.time.Clock()

    board = chess.Board()
    images = load_images()

    selected_square = None
    running = True
    game_over = False

    while running:
        draw_board(win)
        draw_pieces(win, board, images)
        pygame.display.flip()
        clock.tick(60)

        if board.is_game_over():
            print("Game Over:", board.result())
            game_over = True

        for event in pygame.event.get():
            if event.type == pygame.QUIT:
                running = False

            if not board.is_game_over() and board.turn == chess.WHITE:
                if event.type == pygame.MOUSEBUTTONDOWN:
                    square = get_square(pygame.mouse.get_pos())
                    if selected_square is None:
                        if board.piece_at(square) and board.piece_at(square).color == chess.WHITE:
                            selected_square = square
                    else:
                        move = chess.Move(from_square=selected_square, to_square=square)
                        if move in board.legal_moves:
                            board.push(move)
                            selected_square = None
                        else:
                            selected_square = None

        if not board.is_game_over() and board.turn == chess.BLACK:
            pygame.time.wait(500)
            ai_move = get_best_move(model, board)
            if ai_move:
                board.push(ai_move)

    pygame.quit()

if __name__ == "__main__":
    main()
